// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package com.nemnous.proto;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nemnous.proto.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string department = 3;</code>
   * @return The department.
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 3;</code>
   * @return The bytes for department.
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();
}
