// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package com.nemnous.proto;

public final class Employees {
  private Employees() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nemnous_proto_GetEmployeeByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nemnous_proto_GetEmployeeByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nemnous_proto_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nemnous_proto_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017employees.proto\022\021com.nemnous.proto\"$\n\026" +
      "GetEmployeeByIdRequest\022\n\n\002id\030\001 \001(\005\"8\n\010Em" +
      "ployee\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\022\n\ndepa" +
      "rtment\030\003 \001(\t2l\n\017EmployeeService\022Y\n\017getEm" +
      "ployeeById\022).com.nemnous.proto.GetEmploy" +
      "eeByIdRequest\032\033.com.nemnous.proto.Employ" +
      "eeB\025\n\021com.nemnous.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nemnous_proto_GetEmployeeByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nemnous_proto_GetEmployeeByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nemnous_proto_GetEmployeeByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_nemnous_proto_Employee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nemnous_proto_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nemnous_proto_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Department", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
