// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package com.nemnous.proto;

public interface GetEmployeeByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nemnous.proto.GetEmployeeByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
